
const foods=[
  {value: '0', label: "肯德基"},
  {value: '1', label: "德克士"},
  {value: '2', label: "汉堡王"},
  {value: '3', label: "麦当劳"},
  {value: '4', label: "华莱士"},
  {value: '5', label: "棒约翰"},
  {value: '6', label: "米线"},
  {value: '7', label: "米粉"},
  {value: '8', label: "米饭快餐"},
  {value: '9', label: "馄饨"},
  {value: '10', label: "螺蛳粉"},
  {value: '11', label: "黄焖鸡"},
  {value: '12', label: "炸鸡"},
  {value: '13', label: "牛肉汤"},
  {value: '14', label: "拉面"},
  {value: '15', label: "烩面"},
  {value: '16', label: "热干面"},
  {value: '17', label: "刀削面"},
  {value: '18', label: "油泼面"},
  {value: '19', label: "黄焖鸡"},
  {value: '20', label: "炒面"},
  {value: '21', label: "炸酱面"},
  {value: '22', label: "担担面"},
  {value: '23', label: "酸辣粉"},
  {value: '24', label: "土豆粉"},
  {value: '25', label: "凉皮"},
  {value: '26', label: "米皮"},
  {value: '27', label: "麻辣烫"},
  {value: '28', label: "香锅"},
  {value: '29', label: "肉夹馍"},
  {value: '30', label: "羊肉汤"},
  {value: '31', label: "炒饭"},
  {value: '32', label: "盖浇饭"},
  {value: '33', label: "卤肉饭"},
  {value: '34', label: "烤肉饭"},
  {value: '35', label: "炸鸡饭"},
  {value: '36', label: "驴肉汤"},
  {value: '37', label: "驴肉火烧"},
  {value: '38', label: "烤串"},
  {value: '39', label: "披萨"},
  {value: '40', label: "烤鸭"},
  {value: '41', label: "寿司"},
  {value: '42', label: "生煎"},
  {value: '43', label: "炒年糕"},
  {value: '44', label: "小火锅"},
  {value: '45', label: "拌面"},
  {value: '46', label: "随便吃点"},
  {value: '47', label: "烤红薯"},
  {value: '48', label: "泡面"},
  {value: '49', label: "土豆泥"},
  {value: '50', label: "不吃香菜"},
  // {value: '', label: ""},
  {value: '9999', label: "今天不吃了"},

]
export {
 foods,
};
